apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: careers-stage
  name: careers-nodeport
  namespace: careers-stage
spec:
  type: NodePort
  selector:
    app: careers-stage
    type: web
  ports:
    - name: http
      port: 80
      targetPort: 8000
