apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: snippets-stats
  name: snippets-stats-nodeport
  namespace: snippets-stats
spec:
  type: NodePort
  selector:
    app: snippets-stats
  ports:
    - name: https
      port: 443
      targetPort: 8000

