
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: sumo-{{ TARGET_ENVIRONMENT }}
    type: env
  name: {{ SUMO_SECRETS_NAME }}
  namespace: sumo-{{ TARGET_ENVIRONMENT }}
type: Opaque
data:
  aws-access-key-id: 
  aws-s3-custom-domain:
  aws-secret-access-key: 
  aws-storage-bucket-name: 
  broker-url: 
  cache-url: 
  database-read-only-url: 
  database-url: 
  es-http-auth: 
  es-urls: 
  redis-default-url: 
  redis-helpfulvotes-url: 
  secret-key: 
