apiVersion: v1
kind: Pod
metadata:
  name: mdn-backup-test
spec:
    containers:
    - name: mdn-backup-test
      env:
        - name: LOCAL_DIR
          value: /mdn/www/
        - name: REMOTE_DIR
          value: /backups/mdn/
        - name: BUCKET
          value: s3://mdn-shared-backup
        - name: PUSH_OR_PULL
          value: PUSH
        - name: AWS_REGION
          value: us-west-2
        - name: AWS_S3SYNC_PAGE_SIZE
          value: "100"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: access_key
              name: mdn-backup-secrets
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secret_key
              name: mdn-backup-secrets
        - name: DEADMANSSNITCH_URL
          valueFrom:
            secretKeyRef:
              key: DEADMANSSNITCH_URL
              name: mdn-backup-secrets
      image: quay.io/mozmar/mdn-backup:758c79a0fde3
      imagePullPolicy: IfNotPresent
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
      - mountPath: /mdn
        name: mdn-shared
    volumes:
    - name: mdn-shared
      persistentVolumeClaim:
        claimName: mdn-shared

