apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: bedrock-prod
  name: bedrock-nodeport
  namespace: bedrock-prod
spec:
  type: NodePort
  selector:
    app: bedrock-prod
    type: web
  ports:
    - name: https
      port: 443
      targetPort: 8000
